---TABLES
CREATE TABLE book(
                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     book_type_id INT NOT NULL,
                     writer_id INT NOT NULL,
                     name VARCHAR(100) NOT NULL,
                     isbn_no VARCHAR(25) NOT NULL,
                     description VARCHAR(250),
                     FOREIGN KEY(book_type_id) REFERENCES book(id),
                     FOREIGN KEY(writer_id) REFERENCES writer(id)
);

CREATE  TABLE  book_type(
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(50) NOT NULL
);

CREATE TABLE loaned_book(
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id INT NOT NULL,
                            book_id INT NOT NULL,
                            loaned_date DATE NOT NULL,
                            return_date DATE NOT NULL,
                            FOREIGN KEY(user_id) REFERENCES user(id),
                            FOREIGN KEY(book_id) REFERENCES book(id)

);
CREATE TABLE writer(
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(50) NOT NUll,
                       surname VARCHAR(50) NOT NUll,

);
CREATE TABLE user(
                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     firstname VARCHAR(50) NOT NUll,
                     surname VARCHAR(50) NOT NUll,
                     email VARCHAR(50) NOT NUll,
                     birth_date DATE NOT NULL,
                     phone_number VARCHAR(50) NOT NULL
);